export { default as Bookmark2 } from './Bookmark2'
export { default as Firstpagedesign } from './Firstpagedesign'
export { default as Like2 } from './Like2'
export { default as Star7 } from './Star7'
export { default as Techframe } from './Techframe'
export { default as XpertHunt } from './XpertHunt'
export { default as XpertHuntBlack } from './XpertHuntBlack'